@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

participant ":Customer" as Customer
participant ":ReviewController" as Controller
participant ":ReviewService" as ReviewService
participant ":ProductService" as ProductService
participant ":ReviewRepository" as Repository
participant ":ProductRepository" as ProductRepository
participant "list:List<Reviews>" as List

activate Customer

Customer -> Controller : GET getApprovedReviews(productId)
Controller -> ProductService: findOne(productId)
ProductService -> ProductRepository: findById(productId)
ProductRepository --> ProductService: product
ProductService --> Controller: product
Controller -> ReviewService : findApprovedReviews(productId)
ReviewService -> Repository : findApprovedReviews(productId)
Repository --> ReviewService : list
ReviewService --> Controller : list
Controller --> Customer : list


@enduml
