@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

participant ":Customer" as Customer
participant ":ReviewController" as Controller
participant ":ReviewService" as Service
participant ":ReviewRepository" as Repository
participant "list:List<Reviews>" as List

Customer -> Controller : GET Approved Reviews for a Product
Controller -> ProductService : findOne(productId)
ProductService -> ProductRepository : findById(productId)
ProductRepository --> ProductService : product
ProductService --> Controller : product
Controller -> Service : findApprovedReviewsByDate(productId)
Service -> Repository : findApprovedReviewsByDate(productId)
Repository --> Service : listReviews
Service --> Controller : listReviews
Controller --> Customer : listReviews

@enduml
