@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttributeIconSize 0
hide circle
hide methods

class Product {
    - productID
    - name
    - description
    - images
    - SKU
    - version
    - List<Review> listReviews
}

class Review {
    - reviewID
    - text
    - rating
    - upVote
    - downVote
    - funnyFact
    - dataTime
    - status
    - version
}

Product "1" -right-- "*" Review: has >
@enduml
