@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

participant ":RegisteredCustomer" as Customer
participant ":ReviewController" as Controller
participant ":ReviewService" as Service
participant ":ReviewRepository" as Repository
participant "list:List<Reviews>" as List

Customer -> Controller : GET findMyReviews()
Controller -> Service : findMyReviews(Long id)
Service -> Repository : findMyReviews(Long id)
Repository -> Repository : findMyReviews(Long customerId)
Repository --> Service : list
Service --> Controller : list
Controller --> Customer : list

@enduml