@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Customer" as Customer
participant "System" as System

activate Customer

Customer -> System: Asks to show catalog of products
System --> Customer: Return catalog of products
Customer -> System: Asks to get the aggregated rating of a selected product
System --> Customer: Return frequency table of the aggregated rating



@enduml
