@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

participant ":Moderator" as Moderator
participant ":ReviewController" as Controller
participant ":ReviewService" as Service
participant ":ReviewRepository" as Repository

Moderator -> Controller : PUT partialUpdate(reviewId,state)
Controller -> Service : partialUpdate(Long id, Review resource, long parseLong)
Service -> Repository : partialUpdate(Long id, Review resource, long parseLong)
Repository -> Repository : applyPatch(Review review, Long desiredVersion)
Repository --> Service : success
Service --> Controller : success
Controller --> Moderator : success

@enduml