@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttributeIconSize 0
hide circle
hide methods

class User {
    - Id
    - username
    - password
    - email
    - role
}

class Review {
    - reviewID
    - text
    - rating
    - upVote
    - downVote
    - funnyFact
    - dataTime
    - status
    - version
}

User "1" -right-- "*" Review: create >
@enduml
