@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

participant ":Customer" as Customer
participant ":ReviewController" as Controller
participant ":ReviewService" as Service
participant ":Review" as Review
participant "reviewObj" as review
participant ":ReviewRepository" as Repository

Customer -> Controller : POST rate
Controller -> ProductService : findOne(productId)
ProductService -> ProductRepository : findById(productId)
ProductRepository --> ProductService : product
ProductService --> Controller : product
Controller -> Service : create(resource)
Service -> Review : newFrom(resource)
Review -> review** : new()
review -> review : validate()
review --> review : setRating(rating)
review --> Review : obj
Review --> Service : obj
Service -> Repository : save(obj)
Repository --> Service : success
Service --> Controller : success
Controller --> Customer : success

@enduml
