@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttributeIconSize 0
hide circle
hide methods

class Product {
    - productID
    - name
    - description
    - images
    - SKU
}

class Review {
    - reviewID
    - text
    - rating
    - upvote
    - downvote
    - date
    - status
    - funnyFact
}

class User {
    - username
    - password
    - email
    - role
}

User "1" -down-- "*" Review: vote >
Product "1" -right-- "*" Review: has >
@enduml
