@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttributeIconSize 0
hide circle
hide methods


class Product {
    - productID
    - name
    - description
    - images
    - SKU
}


@enduml
