@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant "System" as System

activate User

User -> System: Asks to show catalog of products
System --> User: Return catalog of products
User -> System: Selects a product
System --> User: Show selected product
User -> System: Asks to see his reviews
System --> User: Show Customer reviews
User -> System: Delete review
System -> System: Check if review has votes
group alt (Review has votes)
System --> User: Informs that is impossible to delete
end alt
group alt (Review has no votes)
System --> User: Asks for confirmation
User -> System: Confirms
System --> User: Informs of success
end alt
@enduml
