@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Moderator" as Moderator
participant "System" as System

activate Moderator

Moderator -> System: Asks all pending reviews
System --> Moderator: Return all pending reviews
Moderator -> System: Selects a review
System --> Moderator: Show the review and asks to accept or reject
Moderator -> System: Return response
group alt (response is true)
System --> Moderator: Accepted the review
end alt
group alt (response is false)
System --> Moderator: Reject the review
end alt



@enduml
