@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

participant ":Customer" as Customer
participant ":ReviewController" as Controller
participant ":ReviewService" as Service
participant ":Review" as Review
participant "reviewObj" as review
participant ":ReviewRepository" as Repository

Customer -> Controller : POST create()
Controller -> Service : create(review)
Service -> Review : newFrom(review)
Review -> review** : new()
review -> review : validate()
review --> review : setState("Pending")
review --> Review : review
Review --> Service : review
Service -> Repository : save(review)
Repository --> Service : success
Service --> Controller : success
Controller --> Customer : success

@enduml
